//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSRecord
    {
        public int id { get; set; }
        public string batchNumber { get; set; }
        public Nullable<byte> uploaded { get; set; }
        public Nullable<decimal> Unit_Cost { get; set; }
        public string Posting_Status { get; set; }
        public string TRX_Location { get; set; }
        public string Document_Number { get; set; }
        public string Item_Description { get; set; }
        public string TRX_QTY { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> dateModified { get; set; }
        public string ProdId { get; set; }
        public string ProdName { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
    }
}
